---
title: "farewell_address"
author: "Simone Chu"
date: "4/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidytext)
library(ggplot2)
library(gt)
library(janitor)
library(tidyverse)
```

```{r}
# FOR OBAMA'S FAREWELL ADDRESS
fw_obama <- paste(readLines("fw_obama.html"))

fw_obama <- data.frame(fw_obama, stringsAsFactors = FALSE)

  # Before I could work with the transcripts, I needed to read them out of their respective
  # html files and into a dataframe. 

fw_obama_tidy <- fw_obama %>%
  unnest_tokens(word, fw_obama) %>%
  filter(word != "p")

  # I then used unnest_tokens to turn each word into its own value. 

  # Paragraph breaks were denoted with a "<p>", so I filtered that out because it was recorded
  # as appearing the most frequently. 

fw_obama_sentiment <- fw_obama_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment)

  # I chose to use the "bing" sentiments dictionary for my purposes because I didn't particularly
  # need specific emotions assigned to each word -- positive and negative was good enough. 

  # Rinse and repeat! 

# FOR BUSH'S FAREWELL ADDRESS
fw_bush <- paste(readLines("fw_bush.html"))

fw_bush <- data.frame(fw_bush, stringsAsFactors = FALSE)

fw_bush_tidy <- fw_bush %>%
  unnest_tokens(word, fw_bush) %>%
  filter(word != "p")

fw_bush_sentiment <- fw_bush_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment)

# FOR CLINTON'S FAREWELL ADDRESS
fw_clinton <- paste(readLines("fw_clinton.html"))

fw_clinton <- data.frame(fw_clinton, stringsAsFactors = FALSE)

fw_clinton_tidy <- fw_clinton %>%
  unnest_tokens(word, fw_clinton) %>%
  filter(word != "p")

fw_clinton_sentiment <- fw_clinton_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment)

```

```{r TOPTEN}
posneg <- c("negative" = "#46b5e0", "positive" = "#fdcb6e")

# Obama Farewell Address
fwobama_topten <- fw_obama_sentiment %>%
  arrange(desc(n)) %>%
  slice(1:10) %>%
  # Make word a factor in order of n
  mutate(word = reorder(word, n)) %>% 
  
  ggplot(aes(x = word, y = n, fill = sentiment)) + 
  geom_col() + 
  scale_fill_manual(values=posneg) +
  xlab("Word") + 
  ylab("Number of Instances") + 
  labs(title = "Top 10 Most Used Words in Obama's Farewell Address",
       fill = "Sentiment") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

write_rds(fwobama_topten, 
          "~/Desktop/presidential_speeches/presidential-speeches/fwobama_topten.rds")

# Bush Farewell Address
fwbush_topten <- fw_bush_sentiment %>%
  arrange(desc(n)) %>%
  slice(1:10) %>%
  # Make word a factor in order of n
  mutate(word = reorder(word, n)) %>% 
  
  ggplot(aes(x = word, y = n, fill = sentiment)) + 
  geom_col() + 
  scale_fill_manual(values=posneg) +
  xlab("Word") + 
  ylab("Number of Instances") + 
  labs(title = "Top 10 Most Used Words in Bush's Farewell Address",
       fill = "Sentiment") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

write_rds(fwbush_topten, 
          "~/Desktop/presidential_speeches/presidential-speeches/fwbush_topten.rds")

# Clinton Farewell Address
fwclinton_topten <- fw_clinton_sentiment %>%
  arrange(desc(n)) %>%
  slice(1:10) %>%
  # Make word a factor in order of n
  mutate(word = reorder(word, n)) %>% 
  
  ggplot(aes(x = word, y = n, fill = sentiment)) + 
  geom_col() + 
  scale_fill_manual(values=posneg) +
  xlab("Word") + 
  ylab("Number of Instances") + 
  labs(title = "Top 10 Most Used Words in Clinton's Farewell Address",
       fill = "Sentiment") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

write_rds(fwclinton_topten, 
          "~/Desktop/presidential_speeches/presidential-speeches/fwclinton_topten.rds")
```


```{r OVER_TIME}

# OBAMA FAREWELL ADDRESS
fwobama_ot <- fw_obama_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  mutate(row = row_number()) %>%
  count(index =  row %/% 10, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  
  ggplot(aes(index, sentiment, fill = sentiment)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(title = "How the Tone Changes",
       subtitle = "A plot of density of emotion words over the course of the Farewell Address.") + 
  xlab("Duration of Speech") +
  ylab("Expression") +
  theme(axis.text.x=element_blank())

write_rds(fwobama_ot, 
          "~/Desktop/presidential_speeches/presidential-speeches/fwobama_ot.rds")

# BUSH FAREWELL ADDRESS
fwbush_ot <- fw_bush_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  mutate(row = row_number()) %>%
  count(index =  row %/% 6, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  
  ggplot(aes(index, sentiment, fill = sentiment)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(title = "How the Tone Changes",
       subtitle = "A plot of density of emotion words over the course of the Farewell Address.") + 
  xlab("Duration of Speech") +
  ylab("Expression") +
  theme(axis.text.x=element_blank())

write_rds(fwbush_ot, 
          "~/Desktop/presidential_speeches/presidential-speeches/fwbush_ot.rds")

# CLINTON FAREWELL ADDRESS
fwclinton_ot <- fw_clinton_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  mutate(row = row_number()) %>%
  count(index =  row %/% 6, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  
  ggplot(aes(index, sentiment, fill = sentiment)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(title = "How the Tone Changes",
       subtitle = "A plot of density of emotion words over the course of the Farewell Address.") + 
  xlab("Duration of Speech") +
  ylab("Expression") +
  theme(axis.text.x=element_blank())

write_rds(fwbush_ot, 
          "~/Desktop/presidential_speeches/presidential-speeches/fwclinton_ot.rds")
```

```{r FINAL_APPROVAL_RATING}

approv <- read_csv("approval_ratings.csv") %>%
  clean_names()

# Obama
obama_approval <- approv %>%
  filter(president == "Obama") %>%
  select(-president) %>%
  gt() %>%
  tab_header(title = "Changes in Approval Rating Over Term",
             subtitle = "Barack Obama, 2009 - 2017") %>%
  tab_source_note(md("Source: UCSB Presidency Project")) %>%
  fmt_percent(columns = vars(approve, disapprove, no_opinion), decimals = 0) %>%
  cols_label(time = " ",
             approve = "Approve",
             disapprove = "Disapprove",
             no_opinion = "No Opinion") %>%
  as_raw_html() 

write_rds(obama_approval, 
          "~/Desktop/presidential_speeches/presidential-speeches/obama_approval.rds")

# Bush
bush_approval <- approv %>%
  filter(president == "Bush") %>%
  select(-president) %>%
  gt() %>%
  tab_header(title = "Changes in Approval Rating Over Term",
             subtitle = "George W. Bush, 2001 - 2009") %>%
  tab_source_note(md("Source: UCSB Presidency Project")) %>%
  fmt_percent(columns = vars(approve, disapprove, no_opinion), decimals = 0) %>%
  cols_label(time = " ",
             approve = "Approve",
             disapprove = "Disapprove",
             no_opinion = "No Opinion") %>%
  as_raw_html() 

write_rds(bush_approval, 
          "~/Desktop/presidential_speeches/presidential-speeches/bush_approval.rds")

# Clinton
clinton_approval <- approv %>%
  filter(president == "Clinton") %>%
  select(-president) %>%
  gt() %>%
  tab_header(title = "Changes in Approval Rating Over Term",
             subtitle = "Bill Clinton, 1993 - 2001") %>%
  tab_source_note(md("Source: UCSB Presidency Project")) %>%
  fmt_percent(columns = vars(approve, disapprove, no_opinion), decimals = 0) %>%
  cols_label(time = " ",
             approve = "Approve",
             disapprove = "Disapprove",
             no_opinion = "No Opinion") %>%
  as_raw_html() 

write_rds(clinton_approval, 
          "~/Desktop/presidential_speeches/presidential-speeches/clinton_approval.rds")


```

